name: Build and Deploy Nightly

on:
  push:
    branches:
      - "dev"
  workflow_dispatch :
permissions:
  contents: write
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
      name : Build Flex-rs
      strategy:
        matrix:
          os: [ubuntu-latest, windows-latest]
      runs-on: ${{ matrix.os }}

      steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose

      - name: Upload Nightly
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          name: Nightly Release
          body: "
            Higtly Experimental Nighty Build of Flex-rs
            "
          files: |
            ./target/release/flex-rs.exe
            ./target/release/flex-rs
