name: Build and Deploy Nightly

on:
  push:
    branches:
      - "dev"
  workflow_dispatch :
permissions:
  contents: write
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
      name : Build Flex-rs
      strategy:
        matrix:
          os: [ubuntu-latest, windows-latest]
      runs-on: ${{ matrix.os }}
    
      steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --locked --verbose

      - name: Upload Artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: binaries-${{ matrix.os }}
          path: |
            target/debug/

  deploy:
    name : "Publish Nightly Build"
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v8.0.1
        with:
          path: ./artifacts
          merge-multiple: true

      - name: Upload Nightly
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          name: Nightly Release @ $$
          body: "Higtly Experimental Nighty Build of Flex-rs"
          files: |
            ./artifacts/flex-rs.exe
            ./artifacts/flex-rs
